services:
  web-check:
    image: lissy93/web-check:latest
    container_name: web-check
    restart: unless-stopped
    x-runtipi:
      is_main: true
      internal_port: 3000
x-runtipi:
  schema_version: 2
